### ISSUE TITLE
Missing gems when running tests

### ISSUE THREAD

**Issue by synth** [customink/cookiecutter-ruby#5]
When I run `./bin/test`, I get: 

```
Could not find aws-partitions-1.392.0 in any of the sources
Run `bundle install` to install missing gems.
```

This started once I added the `aws-sdk-ssm` gem.  I don't have any issue running the tests without using Docker (eg `./bin/test`) and don't have any issues running the lambda on AWS. 

I tried adding this to the Dockerfile, but it didn't work: 
```
COPY Gemfile Gemfile.lock ./
RUN bundle install
```

Any ideas?

**Comment by metaskills** [comment]
When running (https://github.com/customink/cookiecutter-ruby/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/bin/test) it will use Docker compose to share the present working directory (https://github.com/customink/cookiecutter-ruby/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L16) and call `bin/_test` inside the container. 

Basically you want to run `bin/setup` (https://github.com/customink/cookiecutter-ruby/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/bin/setup) which will call `bin/_setup` (https://github.com/customink/cookiecutter-ruby/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/bin/_setup) and that does the bundle install. 

The whole basis of the Docker usage in these projects is to do nothing more than host the PWD. Copying things from the PWD into the image start to tear that apart and can cause issues.

**Comment by synth** [comment]
awesome, worked! thanks! ok, so good to know, we should call `bin/setup` anytime we need to call bundle install and run tests.
